import argparse
import json
import os
import sys
from typing import Any, Dict, List, Optional
from urllib import error

try:
	from .llm_client import LLMChatClient, PROVIDER_PRESETS
except ImportError:
	from llm_client import LLMChatClient, PROVIDER_PRESETS


SYSTEM_PROMPT = (
	"You are a binary security analyst. Analyze decompiled pseudocode and return strictly valid JSON."
)


def build_user_prompt(func: Dict[str, Any]) -> str:
    prompt=f'''System/Instruction Prompt:
You are a top binary security expert and a static data flow analysis engine. Your core task is to analyze the pseudo C code generated by Ghidra decompilation and perform semantic dimensionality reduction and feature extraction. You need to ignore low-level compiler optimization residues unrelated to the core business logic, focus on tracking the processing of variables, and accurately identify potential taint sources, sinks, and subfunction calls. Please output the analysis results strictly according to the required JSON format, without including any additional Markdown markup or explanatory text.

User Prompt:
Please analyze the following pseudo C code decompiled by Ghidra and extract the relevant semantics and attributes:

[Function Code to be Analyzed]
{func.get('pseudocode', '')}

[Analysis Tasks and Output Constraints]
Please return a JSON object that must include the following fields:
1. "description" (String): Briefly describe the core function of this function in one or two natural language sentences .
2. "variable_operations" (Array of Objects): Extract the processing constraints on variables (especially externally passed parameters) inside the function. Each object includes "variable_name" and "operation_summary" (for example: "appended to buffer after filtering", "bitwise AND with 0xff").
3. "sources" (Array of Strings): Extract function or variable names that receive external untrusted input (corresponding to S_f). If none, leave as an empty array.
4. "sinks" (Array of Strings): Extract sensitive operations or system calls that could lead to memory corruption, command execution, etc. If none, leave as an empty array.
5. "child_functions" (Array of Strings): List the names of all sub-functions called within this function. If none, leave as an empty array.
6. "is_normal_function" (Boolean): If both "sources" and "sinks" are empty arrays, set this to true; otherwise, set it to false.'''
    
    
    return prompt


def extract_json(text: str) -> Optional[Dict[str, Any]]:
	text = text.strip()
	try:
		return json.loads(text)
	except Exception:
		pass

	start = text.find("{")
	end = text.rfind("}")
	if start == -1 or end == -1 or end <= start:
		return None
	try:
		return json.loads(text[start : end + 1])
	except Exception:
		return None


def analyze_functions(functions: List[Dict[str, Any]], client: LLMChatClient) -> None:
	for idx, func in enumerate(functions):
		pseudocode = (func.get("pseudocode") or "").strip()
		prompt = build_user_prompt(func)
		func["llm_description_prompt"] = prompt

		if not pseudocode:
			func["llm_description"] = "No pseudocode available."
			func["llm_unrestricted_input_vulnerable"] = False
			func["llm_vulnerability_reason"] = "No code to analyze."
			func["llm_confidence"] = "low"
			continue

		try:
			raw = client.chat_completion(system_prompt=SYSTEM_PROMPT, user_prompt=prompt)
			parsed = extract_json(raw)

			if parsed is None:
				func["llm_description"] = raw.strip()
				func["llm_unrestricted_input_vulnerable"] = False
				func["llm_vulnerability_reason"] = "Failed to parse model JSON response."
				func["llm_confidence"] = "low"
				func["llm_analysis_raw"] = raw
			else:
				func["llm_description"] = parsed.get("description", "")
				func["llm_unrestricted_input_vulnerable"] = bool(
					parsed.get("unrestricted_input_vulnerable", False)
				)
				func["llm_vulnerability_reason"] = parsed.get(
					"vulnerability_reason", ""
				)
				func["llm_confidence"] = parsed.get("confidence", "medium")
				func["llm_analysis_raw"] = raw

		except error.HTTPError as e:
			msg = e.read().decode("utf-8", errors="replace") if hasattr(e, "read") else str(e)
			func["llm_description"] = ""
			func["llm_unrestricted_input_vulnerable"] = False
			func["llm_vulnerability_reason"] = f"HTTP error: {msg}"
			func["llm_confidence"] = "low"
		except Exception as e:
			func["llm_description"] = ""
			func["llm_unrestricted_input_vulnerable"] = False
			func["llm_vulnerability_reason"] = f"Analysis failed: {e}"
			func["llm_confidence"] = "low"

		print(f"[{idx + 1}/{len(functions)}] analyzed {func.get('name', '<unknown>')}")


def main() -> int:
	provider_choices = ", ".join(sorted(PROVIDER_PRESETS))
	parser = argparse.ArgumentParser(
		description="Analyze each function pseudocode in a Ghidra JSON via LLM."
	)
	parser.add_argument("input_json", help="Path to input JSON file")
	parser.add_argument(
		"-o",
		"--output",
		default=None,
		help="Output JSON path (default: overwrite input file)",
	)
	parser.add_argument(
		"--provider",
		default=os.getenv("LLM_PROVIDER", "openai"),
		help=(
			f"LLM provider preset (default: openai). Supported: {provider_choices}. "
			"Use compatible with --base-url for any OpenAI-compatible vendor."
		),
	)
	parser.add_argument(
		"--api-key",
		default=None,
		help="API key override. If omitted, the provider-specific environment variable is used.",
	)
	parser.add_argument(
		"--model",
		default=os.getenv("LLM_MODEL", "gpt-5.3-codex"),
		help="Model name (default: env LLM_MODEL or gpt-5.3-codex)",
	)
	parser.add_argument(
		"--base-url",
		default=None,
		help="API base URL override. If omitted, the provider-specific environment variable or default base URL is used.",
	)
	parser.add_argument(
		"--timeout",
		type=int,
		default=120,
		help="HTTP timeout in seconds (default: 120)",
	)
	args = parser.parse_args()

	try:
		client = LLMChatClient(
			provider=args.provider,
			model=args.model,
			api_key=args.api_key,
			base_url=args.base_url,
			timeout=args.timeout,
		)
	except ValueError as e:
		print(str(e), file=sys.stderr)
		return 1

	try:
		with open(args.input_json, "r", encoding="utf-8") as f:
			data = json.load(f)
	except Exception as e:
		print(f"Failed to read input JSON: {e}", file=sys.stderr)
		return 1

	functions = (
		data.get("result", {}).get("functions", [])
		if isinstance(data, dict)
		else []
	)

	if not isinstance(functions, list):
		print("Invalid input JSON: result.functions must be a list", file=sys.stderr)
		return 1

	analyze_functions(functions, client=client)

	output_path = args.output or args.input_json
	try:
		with open(output_path, "w", encoding="utf-8") as f:
			json.dump(data, f, ensure_ascii=False, indent=2)
	except Exception as e:
		print(f"Failed to write output JSON: {e}", file=sys.stderr)
		return 1

	print(f"Done. Output: {output_path}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())

